// The Operating Intelligence taxonomy — the ONE classification system for every
// knowledge object in the Brain:  CLASS → DOMAIN → TYPE → SUBTYPE (+ open tags).
//
// Three core intelligence classes (Business Reality / Playbooks / Organizational
// Learning) plus two supporting systems (Platform Intelligence / Performance
// Memory). Domain and Type are predefined; Subtype is controlled-but-extensible
// (the compiler reuses existing values and proposes new ones into an approval
// queue); Tags are completely open.
//
// Pure data + helpers — safe to import from client components and the server.
// Persisted extensions (proposed/approved subtypes etc.) live in taxonomy_values.

// ---------------------------------------------------------------------------
// Intelligence classes
// ---------------------------------------------------------------------------

export type IntelligenceClass =
  | "business_reality"
  | "playbook"
  | "organizational_learning"
  | "platform_intelligence"
  | "performance_memory"
  | "raw_archive";

export interface ClassDef {
  id: IntelligenceClass;
  label: string;
  question: string;
  description: string;
  /** Core classes are the three the human chooses at ingest; supporting ones are system-fed. */
  core: boolean;
}

export const INTELLIGENCE_CLASSES: ClassDef[] = [
  {
    id: "business_reality",
    label: "Business Reality",
    question: "What is true / what happened?",
    description: "Everything that tells the Brain what is actually happening inside PractiScale: company truth, founder thinking, customers, sales calls, operations, people, proof, brand, approved content.",
    core: true,
  },
  {
    id: "playbook",
    label: "Playbook",
    question: "How should we think / what should work?",
    description: "Curated frameworks, principles, tactics and systems from experts, books, consultants, employees and our own discoveries.",
    core: true,
  },
  {
    id: "organizational_learning",
    label: "Organizational Learning",
    question: "What have WE learned?",
    description: "The memory of what PractiScale decided, implemented, measured and learned — mostly generated by the Brain from real work, then confirmed by a human.",
    core: true,
  },
  {
    id: "platform_intelligence",
    label: "Platform Intelligence",
    question: "How does each platform work?",
    description: "Per-platform formats, audience behaviour, hooks, distribution mechanics, native features, constraints and tested learnings.",
    core: false,
  },
  {
    id: "performance_memory",
    label: "Performance Memory",
    question: "What results occurred?",
    description: "Structured results: content, sales, marketing, customer and employee performance, experiment outcomes.",
    core: false,
  },
  {
    id: "raw_archive",
    label: "Raw Archive",
    question: "What was the original source?",
    description: "Unprocessed source material kept for provenance and history. Low authority; searched only when explicitly requested.",
    core: false,
  },
];

export const CORE_CLASSES: IntelligenceClass[] = ["business_reality", "playbook", "organizational_learning"];

export function isIntelligenceClass(v: unknown): v is IntelligenceClass {
  return typeof v === "string" && INTELLIGENCE_CLASSES.some((c) => c.id === v);
}

// ---------------------------------------------------------------------------
// Domains — one list for the whole Brain (a domain is NOT an object type)
// ---------------------------------------------------------------------------

export interface DomainDef {
  id: string;
  label: string;
  /** Which classes commonly use this domain (informational; any class may use any domain). */
  classes: IntelligenceClass[];
  /** Stable ref prefix for objects in this domain (e.g. MG-001). */
  prefix: string;
}

export const DOMAINS: DomainDef[] = [
  { id: "founder", label: "Founder", classes: ["business_reality"], prefix: "FND" },
  { id: "company", label: "Company", classes: ["business_reality"], prefix: "CO" },
  { id: "customer", label: "Customer", classes: ["business_reality"], prefix: "CUS" },
  { id: "sales", label: "Sales", classes: ["business_reality", "playbook"], prefix: "SAL" },
  { id: "marketing", label: "Marketing", classes: ["business_reality", "playbook"], prefix: "MKT" },
  { id: "content", label: "Content", classes: ["business_reality", "playbook"], prefix: "CON" },
  { id: "offers", label: "Offers", classes: ["business_reality", "playbook"], prefix: "OFF" },
  { id: "customer_success", label: "Customer Success", classes: ["business_reality", "playbook"], prefix: "CS" },
  { id: "management", label: "Management", classes: ["business_reality", "playbook"], prefix: "MG" },
  { id: "leadership", label: "Leadership", classes: ["playbook"], prefix: "LD" },
  { id: "talent_hiring", label: "Talent & Hiring", classes: ["business_reality", "playbook"], prefix: "TAL" },
  { id: "operations", label: "Operations", classes: ["business_reality", "playbook"], prefix: "OPS" },
  { id: "strategy", label: "Strategy", classes: ["playbook"], prefix: "STR" },
  { id: "growth", label: "Growth", classes: ["playbook"], prefix: "GRO" },
  { id: "brand", label: "Brand", classes: ["business_reality"], prefix: "BRD" },
  { id: "platform", label: "Platform", classes: ["platform_intelligence"], prefix: "PI" },
  { id: "finance", label: "Finance", classes: ["business_reality"], prefix: "FIN" },
  { id: "legal", label: "Legal", classes: ["business_reality"], prefix: "LEG" },
  { id: "technology", label: "Technology", classes: ["business_reality"], prefix: "TEC" },
  { id: "people_management", label: "People & Management", classes: ["business_reality"], prefix: "PPL" },
  { id: "other", label: "Other", classes: ["business_reality", "playbook"], prefix: "GEN" },
];

export const DOMAIN_IDS = DOMAINS.map((d) => d.id);

export function isDomain(v: unknown): v is string {
  return typeof v === "string" && DOMAIN_IDS.includes(v);
}

export function domainLabel(id: string | null | undefined): string {
  return DOMAINS.find((d) => d.id === id)?.label ?? (id ? humanize(id) : "—");
}

/** Domains that make sense for a class (for pickers). */
export function domainsForClass(cls: IntelligenceClass): DomainDef[] {
  if (cls === "organizational_learning" || cls === "performance_memory" || cls === "raw_archive") return DOMAINS;
  if (cls === "platform_intelligence") return DOMAINS.filter((d) => d.id === "platform");
  return DOMAINS.filter((d) => d.classes.includes(cls) || d.id === "other");
}

// ---------------------------------------------------------------------------
// Business Reality buckets — the human-facing grouping of reality objects
// (Company Truth, Founder Brain, …). Derived from domain + type + status so it
// never becomes a second competing taxonomy.
// ---------------------------------------------------------------------------

export type RealityBucket =
  | "company_truth"
  | "founder_brain"
  | "customer_intelligence"
  | "sales_intelligence"
  | "operations_intelligence"
  | "people_management"
  | "proof_evidence"
  | "brand_voice"
  | "approved_content"
  | "historical_archive";

export interface BucketDef {
  id: RealityBucket;
  label: string;
  description: string;
  /** The domain the compiler defaults to when the human picks this bucket. */
  domain: string;
  /** Default authority for objects landing in this bucket. */
  authority: AuthorityLevel;
  /** Extra validation: external (social/expert) sources cannot land here directly. */
  guarded?: boolean;
}

export const REALITY_BUCKETS: BucketDef[] = [
  { id: "company_truth", label: "Company Truth", description: "Authoritative current facts: pricing, offers, headcount, policies, processes, targets.", domain: "company", authority: "A1", guarded: true },
  { id: "founder_brain", label: "Founder Brain", description: "Afra's beliefs, experiences, opinions and mental models — in his own words.", domain: "founder", authority: "A3" },
  { id: "customer_intelligence", label: "Customer Intelligence", description: "Complaints, interviews, feedback, ICP evidence, customer language.", domain: "customer", authority: "A4" },
  { id: "sales_intelligence", label: "Sales Intelligence", description: "Calls, scores, objections, won/lost patterns, closer performance.", domain: "sales", authority: "A4" },
  { id: "operations_intelligence", label: "Operations Intelligence", description: "SOPs, processes, fulfillment reports, department structure.", domain: "operations", authority: "A2" },
  { id: "people_management", label: "People & Management", description: "Manager reports, task breakdowns, meetings, team performance.", domain: "people_management", authority: "A2" },
  { id: "proof_evidence", label: "Proof & Evidence", description: "Testimonials, case studies, results the company can cite.", domain: "customer", authority: "A2" },
  { id: "brand_voice", label: "Brand & Voice", description: "Voice guides, positioning, messaging rules.", domain: "brand", authority: "A1" },
  { id: "approved_content", label: "Approved Content", description: "Published or approved pieces that teach style and patterns.", domain: "content", authority: "A2" },
  { id: "historical_archive", label: "Historical / Raw Archive", description: "Things that were true before; kept for history, never resurrected as current.", domain: "other", authority: "C1" },
];

export function isRealityBucket(v: unknown): v is RealityBucket {
  return typeof v === "string" && REALITY_BUCKETS.some((b) => b.id === v);
}

/** Infer the human-facing bucket of a reality object from its classification. */
export function realityBucketOf(o: {
  domain?: string | null;
  object_type?: string | null;
  status?: string | null;
}): RealityBucket {
  if (o.status === "historical" || o.status === "archived") return "historical_archive";
  const t = o.object_type ?? "";
  if (t === "testimonial" || t === "case_study" || t === "proof") return "proof_evidence";
  if (t === "approved_content") return "approved_content";
  switch (o.domain) {
    case "company":
    case "finance":
    case "legal":
    case "technology":
      return "company_truth";
    case "founder":
      return "founder_brain";
    case "customer":
    case "customer_success":
      return "customer_intelligence";
    case "sales":
    case "offers":
      return "sales_intelligence";
    case "operations":
      return "operations_intelligence";
    case "people_management":
    case "management":
    case "talent_hiring":
    case "leadership":
      return "people_management";
    case "brand":
      return "brand_voice";
    case "content":
    case "marketing":
      return "approved_content";
    default:
      return "company_truth";
  }
}

// ---------------------------------------------------------------------------
// Object types
// ---------------------------------------------------------------------------

export interface TypeDef {
  id: string;
  label: string;
  /** Which classes this type belongs to. */
  classes: IntelligenceClass[];
  /** Content-specialised playbook types are only offered for domain=content. */
  contentOnly?: boolean;
}

export const OBJECT_TYPES: TypeDef[] = [
  // Universal playbook object types
  { id: "strategy", label: "Strategy", classes: ["playbook"] },
  { id: "framework", label: "Framework", classes: ["playbook"] },
  { id: "system", label: "System", classes: ["playbook"] },
  { id: "principle", label: "Principle", classes: ["playbook"] },
  { id: "tactic", label: "Tactic", classes: ["playbook"] },
  { id: "structure", label: "Structure", classes: ["playbook"] },
  { id: "diagnostic", label: "Diagnostic", classes: ["playbook"] },
  { id: "mental_model", label: "Mental Model", classes: ["playbook"] },
  { id: "checklist", label: "Checklist", classes: ["playbook"] },
  { id: "process", label: "Process", classes: ["playbook", "business_reality"] },
  { id: "script", label: "Script", classes: ["playbook", "business_reality"] },
  { id: "template", label: "Template", classes: ["playbook"] },
  { id: "metric", label: "Metric", classes: ["playbook", "performance_memory"] },
  { id: "observation", label: "Observation", classes: ["playbook"] },
  // Content-specialised playbook types
  { id: "hook", label: "Hook", classes: ["playbook"], contentOnly: true },
  { id: "story_mechanic", label: "Story Mechanic", classes: ["playbook"], contentOnly: true },
  { id: "retention_mechanic", label: "Retention Mechanic", classes: ["playbook"], contentOnly: true },
  { id: "cta_mechanic", label: "CTA Mechanic", classes: ["playbook"], contentOnly: true },
  { id: "proof_mechanic", label: "Proof Mechanic", classes: ["playbook"], contentOnly: true },
  { id: "delivery_style", label: "Delivery Style", classes: ["playbook"], contentOnly: true },
  { id: "platform_tactic", label: "Platform Tactic", classes: ["playbook"], contentOnly: true },
  { id: "content_structure", label: "Content Structure", classes: ["playbook"], contentOnly: true },
  { id: "content_system", label: "Content System", classes: ["playbook"], contentOnly: true },
  { id: "content_ideation", label: "Content Ideation", classes: ["playbook"], contentOnly: true },
  { id: "content_calendar", label: "Content Calendar", classes: ["playbook"], contentOnly: true },
  { id: "distribution", label: "Distribution", classes: ["playbook"], contentOnly: true },
  { id: "repurposing", label: "Repurposing", classes: ["playbook"], contentOnly: true },
  { id: "content_analytics", label: "Content Analytics", classes: ["playbook"], contentOnly: true },
  // Business Reality types (what the artefact IS)
  { id: "fact", label: "Fact / Truth statement", classes: ["business_reality"] },
  { id: "pricing", label: "Pricing", classes: ["business_reality"] },
  { id: "offer", label: "Offer", classes: ["business_reality"] },
  { id: "policy", label: "Policy", classes: ["business_reality"] },
  { id: "call", label: "Call", classes: ["business_reality"] },
  { id: "call_score", label: "Call Score", classes: ["business_reality"] },
  { id: "transcript", label: "Transcript", classes: ["business_reality"] },
  { id: "meeting", label: "Meeting", classes: ["business_reality"] },
  { id: "report", label: "Report", classes: ["business_reality"] },
  { id: "task_analysis", label: "Task Analysis", classes: ["business_reality"] },
  { id: "kpi_report", label: "KPI Report", classes: ["business_reality"] },
  { id: "sop", label: "SOP", classes: ["business_reality"] },
  { id: "testimonial", label: "Testimonial", classes: ["business_reality"] },
  { id: "case_study", label: "Case Study", classes: ["business_reality"] },
  { id: "complaint", label: "Complaint", classes: ["business_reality"] },
  { id: "interview", label: "Interview", classes: ["business_reality"] },
  { id: "experience", label: "Experience", classes: ["business_reality"] },
  { id: "belief", label: "Belief / Position", classes: ["business_reality"] },
  { id: "note", label: "Note", classes: ["business_reality"] },
  { id: "voice_guide", label: "Voice Guide", classes: ["business_reality"] },
  { id: "approved_content", label: "Approved Content", classes: ["business_reality"] },
  { id: "announcement", label: "Announcement", classes: ["business_reality"] },
  { id: "document", label: "Document", classes: ["business_reality", "raw_archive"] },
  // Organizational Learning lifecycle types
  { id: "decision", label: "Decision", classes: ["organizational_learning"] },
  { id: "implementation", label: "Implementation", classes: ["organizational_learning"] },
  { id: "experiment", label: "Experiment", classes: ["organizational_learning"] },
  { id: "result", label: "Result", classes: ["organizational_learning"] },
  { id: "learning", label: "Learning", classes: ["organizational_learning"] },
  { id: "adaptation", label: "Adaptation", classes: ["organizational_learning"] },
  { id: "postmortem", label: "Postmortem", classes: ["organizational_learning"] },
  { id: "standard", label: "PractiScale Standard", classes: ["organizational_learning"] },
  // Platform Intelligence types
  { id: "format", label: "Format", classes: ["platform_intelligence"] },
  { id: "audience_behavior", label: "Audience Behaviour", classes: ["platform_intelligence"] },
  { id: "platform_hook", label: "Hook (platform)", classes: ["platform_intelligence"] },
  { id: "distribution_mechanic", label: "Distribution Mechanic", classes: ["platform_intelligence"] },
  { id: "native_feature", label: "Native Feature", classes: ["platform_intelligence"] },
  { id: "creative_constraint", label: "Creative Constraint", classes: ["platform_intelligence"] },
  { id: "best_practice", label: "Best Practice", classes: ["platform_intelligence"] },
  { id: "testing_learning", label: "Testing Learning", classes: ["platform_intelligence"] },
  { id: "performance_history", label: "Performance History", classes: ["platform_intelligence", "performance_memory"] },
];

export function isObjectType(v: unknown): v is string {
  return typeof v === "string" && OBJECT_TYPES.some((t) => t.id === v);
}

export function typeLabel(id: string | null | undefined): string {
  return OBJECT_TYPES.find((t) => t.id === id)?.label ?? (id ? humanize(id) : "—");
}

/** Types offered for a class (+ content-only types when the domain is content). */
export function typesFor(cls: IntelligenceClass, domain?: string | null): TypeDef[] {
  return OBJECT_TYPES.filter((t) => t.classes.includes(cls) && (!t.contentOnly || domain === "content"));
}

/** Learning lifecycle order (not every situation needs every step). */
export const LEARNING_LIFECYCLE: string[] = [
  "decision",
  "implementation",
  "experiment",
  "result",
  "learning",
  "adaptation",
  "standard",
];
export const LEARNING_RECORD_TYPES: string[] = [...LEARNING_LIFECYCLE, "postmortem"];

export const LEARNING_REF_PREFIX: Record<string, string> = {
  decision: "DEC",
  implementation: "IMP",
  experiment: "EXP",
  result: "RES",
  learning: "LRN",
  adaptation: "ADP",
  postmortem: "PM",
  standard: "STD",
};

export type LearningStatus =
  | "proposed"
  | "open"
  | "implementing"
  | "measuring"
  | "completed"
  | "validated"
  | "rejected"
  | "archived";

export const LEARNING_STATUSES: { id: LearningStatus; label: string }[] = [
  { id: "proposed", label: "Proposed" },
  { id: "open", label: "Open" },
  { id: "implementing", label: "Implementing" },
  { id: "measuring", label: "Measuring" },
  { id: "completed", label: "Completed" },
  { id: "validated", label: "Validated" },
  { id: "rejected", label: "Rejected" },
  { id: "archived", label: "Archived" },
];

// ---------------------------------------------------------------------------
// Suggested subtypes (seed values; the taxonomy is extensible via the DB)
// ---------------------------------------------------------------------------

export const SUGGESTED_SUBTYPES: Record<string, string[]> = {
  "management/framework": ["accountability", "delegation", "management_leverage", "decision_making", "performance_management", "decision_rights", "manager_dependency"],
  "management/principle": ["delegation", "ownership", "feedback", "prioritisation"],
  "sales/framework": ["discovery", "objection_handling", "closing", "follow_up", "qualification", "trust", "sales_process"],
  "sales/script": ["discovery", "objection_handling", "closing", "follow_up", "cold_outreach"],
  "sales/call": ["high_ticket", "discovery", "closing", "onboarding", "renewal"],
  "marketing/framework": ["cro", "lead_generation", "positioning", "acquisition", "messaging"],
  "marketing/strategy": ["acquisition", "retention", "launch", "channel"],
  "content/hook": ["contrarian", "question", "quote_led", "curiosity", "story", "stat_led"],
  "content/content_structure": ["listicle", "story", "educational", "case_study", "how_to", "comparison"],
  "content/tactic": ["distribution", "engagement", "commenting", "repurposing"],
  "talent_hiring/framework": ["selection", "ownership_signals", "interviewing", "onboarding", "retention"],
  "customer_success/framework": ["onboarding", "retention", "expectation_setting", "churn", "expansion"],
  "offers/strategy": ["pricing", "value", "speed", "guarantee", "packaging"],
  "operations/process": ["fulfillment", "qa", "handoff", "reporting"],
  "strategy/framework": ["prioritisation", "market_selection", "resource_allocation", "positioning"],
  "leadership/principle": ["vision", "standards", "culture", "communication"],
  "growth/framework": ["referral", "partnerships", "expansion", "flywheel"],
  "customer/testimonial": ["video", "written"],
  "customer/case_study": ["client_success", "turnaround"],
  "founder/experience": ["scaling_lesson", "failure", "win", "decision"],
  "founder/belief": ["management", "sales", "content", "growth"],
  "company/pricing": ["standard", "priority", "package"],
};

export function suggestedSubtypes(domain: string | null | undefined, type: string | null | undefined): string[] {
  if (!domain || !type) return [];
  return SUGGESTED_SUBTYPES[`${domain}/${type}`] ?? [];
}

// ---------------------------------------------------------------------------
// Governance: endorsement, implementation, validation, evidence, priority, status
// ---------------------------------------------------------------------------

export type FounderEndorsement = "interested" | "approved" | "practiscale_standard";
export const FOUNDER_ENDORSEMENTS: { id: FounderEndorsement; label: string; hint: string; weight: number }[] = [
  { id: "interested", label: "Interested", hint: "I like this / keep it in the Brain.", weight: 0 },
  { id: "approved", label: "Approved", hint: "I believe in this and want the Brain to use it.", weight: 0.08 },
  { id: "practiscale_standard", label: "PractiScale Standard", hint: "This is how we operate.", weight: 0.18 },
];

export type ImplementationStatus = "not_tested" | "testing" | "implemented";
export const IMPLEMENTATION_STATUSES: { id: ImplementationStatus; label: string }[] = [
  { id: "not_tested", label: "Not tested" },
  { id: "testing", label: "Testing" },
  { id: "implemented", label: "Implemented" },
];

export type InternalValidation = "unvalidated" | "validated" | "modified" | "rejected";
export const INTERNAL_VALIDATIONS: { id: InternalValidation; label: string; weight: number }[] = [
  { id: "unvalidated", label: "Unvalidated", weight: 0 },
  { id: "validated", label: "Validated", weight: 0.1 },
  { id: "modified", label: "Modified", weight: 0.06 },
  { id: "rejected", label: "Rejected", weight: -0.2 },
];

export type EvidenceLevel =
  | "source_teaching"
  | "founder_experience"
  | "internal_data"
  | "validated_experiment"
  | "verified_truth";
export const EVIDENCE_LEVELS: { id: EvidenceLevel; label: string }[] = [
  { id: "source_teaching", label: "Source teaching" },
  { id: "founder_experience", label: "Founder experience" },
  { id: "internal_data", label: "Internal data" },
  { id: "validated_experiment", label: "Validated experiment" },
  { id: "verified_truth", label: "Verified truth" },
];

export type Priority = "core" | "strong" | "normal" | "low";
export const PRIORITIES: { id: Priority; label: string; weight: number }[] = [
  { id: "core", label: "Core", weight: 0.06 },
  { id: "strong", label: "Strong", weight: 0.03 },
  { id: "normal", label: "Normal", weight: 0 },
  { id: "low", label: "Low", weight: -0.04 },
];

export type ObjectStatus = "active" | "draft" | "historical" | "archived";
export const OBJECT_STATUSES: { id: ObjectStatus; label: string }[] = [
  { id: "active", label: "Active" },
  { id: "draft", label: "Draft" },
  { id: "historical", label: "Historical" },
  { id: "archived", label: "Archived" },
];

// ---------------------------------------------------------------------------
// Authority hierarchy — what to believe when information conflicts
// ---------------------------------------------------------------------------

export type AuthorityLevel = "A1" | "A2" | "A3" | "A4" | "A5" | "B1" | "B2" | "B3" | "C1" | "C2" | "C3";

export interface AuthorityDef {
  id: AuthorityLevel;
  label: string;
  /** Retrieval boost in [-0.15, 0.2]; higher = trusted more when relevance ties. */
  weight: number;
  rank: number;
}

export const AUTHORITY_LEVELS: AuthorityDef[] = [
  { id: "A1", label: "Current verified company truth", weight: 0.2, rank: 1 },
  { id: "A2", label: "Verified business data", weight: 0.16, rank: 2 },
  { id: "A3", label: "Founder current position", weight: 0.14, rank: 3 },
  { id: "A4", label: "Customer / call evidence", weight: 0.12, rank: 4 },
  { id: "A5", label: "Organizational learning", weight: 0.12, rank: 5 },
  { id: "B1", label: "Approved PractiScale playbook", weight: 0.08, rank: 6 },
  { id: "B2", label: "Approved external playbook", weight: 0.05, rank: 7 },
  { id: "B3", label: "External source claim", weight: 0, rank: 8 },
  { id: "C1", label: "Historical company information", weight: -0.08, rank: 9 },
  { id: "C2", label: "Raw / unverified information", weight: -0.1, rank: 10 },
  { id: "C3", label: "Archive", weight: -0.15, rank: 11 },
];

export function isAuthority(v: unknown): v is AuthorityLevel {
  return typeof v === "string" && AUTHORITY_LEVELS.some((a) => a.id === v);
}

export function authorityWeight(id: string | null | undefined): number {
  return AUTHORITY_LEVELS.find((a) => a.id === id)?.weight ?? 0;
}

export function authorityLabel(id: string | null | undefined): string {
  return AUTHORITY_LEVELS.find((a) => a.id === id)?.label ?? "Unrated";
}

/**
 * Default authority for an object from its class + governance fields. Authority
 * tells the Brain what to TRUST; the temporal fields tell it whether that trust
 * is still current (see isCurrent()).
 */
export function defaultAuthority(o: {
  intelligence_class: IntelligenceClass;
  domain?: string | null;
  object_type?: string | null;
  status?: string | null;
  founder_endorsement?: string | null;
  internal_validation?: string | null;
  source_platform?: string | null;
  bucket?: RealityBucket | null;
}): AuthorityLevel {
  if (o.status === "archived") return "C3";
  if (o.status === "historical") return "C1";
  switch (o.intelligence_class) {
    case "raw_archive":
      return "C2";
    case "organizational_learning":
      return o.internal_validation === "validated" || o.object_type === "standard" ? "A2" : "A5";
    case "playbook":
      if (o.founder_endorsement === "practiscale_standard") return "B1";
      if (o.internal_validation === "validated") return "B1";
      if (o.founder_endorsement === "approved") return "B2";
      return "B3";
    case "platform_intelligence":
      return o.internal_validation === "validated" ? "A2" : "B3";
    case "performance_memory":
      return "A2";
    case "business_reality": {
      const bucket = o.bucket ?? realityBucketOf(o);
      return REALITY_BUCKETS.find((b) => b.id === bucket)?.authority ?? "A2";
    }
    default:
      return "B3";
  }
}

/** Whether an object is current given its temporal fields (as of `now`). */
export function isCurrent(
  o: { effective_from?: string | null; effective_until?: string | null; status?: string | null },
  now: Date = new Date()
): boolean {
  if (o.status === "historical" || o.status === "archived") return false;
  const t = now.getTime();
  if (o.effective_from && new Date(o.effective_from).getTime() > t) return false;
  if (o.effective_until && new Date(o.effective_until).getTime() <= t) return false;
  return true;
}

// ---------------------------------------------------------------------------
// Content dimensions, platforms, audiences, roles, functions
// ---------------------------------------------------------------------------

export const PLATFORMS = [
  "linkedin",
  "instagram",
  "youtube",
  "x",
  "tiktok",
  "facebook",
  "snapchat",
  "email",
  "website",
  "podcast",
  "universal",
] as const;

export const FORMATS = [
  "short_form_video",
  "long_form_video",
  "text_post",
  "carousel",
  "image",
  "thread",
  "email",
  "newsletter",
  "podcast",
  "article",
  "ad",
  "vsl",
  "landing_page",
  "not_applicable",
] as const;

export const CONTENT_JOBS = ["discovery", "trust", "authority", "nurture", "conversion", "retention"] as const;
export const FUNNEL_STAGES = ["tofu", "mofu", "bofu", "post_purchase"] as const;
export const BRANDS = ["afra_founder", "practiscale", "other"] as const;
export const LENGTHS = ["micro", "short", "medium", "long"] as const;

/** Seed audiences (a dynamic entity — new audiences are added via the taxonomy). */
export const AUDIENCES = [
  "healthcare_practice_owner",
  "agency_founder",
  "entrepreneur",
  "employee",
  "manager",
  "job_candidate",
  "referral_partner",
] as const;

/** Who a playbook applies to. */
export const APPLIES_TO = [
  "founder",
  "executives",
  "managers",
  "team_leaders",
  "employees",
  "closers",
  "setters",
  "marketers",
  "content_team",
  "customer_success",
  "operations",
  "recruiters",
  "universal",
] as const;

export const BUSINESS_FUNCTIONS = [
  "universal",
  "sales",
  "marketing",
  "content",
  "fulfillment",
  "customer_success",
  "crm",
  "operations",
  "finance",
  "hr",
  "leadership",
] as const;

export const BUSINESS_STAGES = ["startup", "scaling", "enterprise"] as const;

/** Social / external platforms — a source from one of these cannot establish Company Truth directly. */
export const EXTERNAL_SOURCE_PLATFORMS = new Set<string>([
  "instagram",
  "youtube",
  "linkedin",
  "x",
  "tiktok",
  "facebook",
  "snapchat",
  "podcast",
  "book",
  "course",
  "article",
  "newsletter",
]);

export const SOURCE_TYPES = ["video", "audio", "text", "book", "course", "call", "meeting", "document", "note", "screenshot", "internal_report", "other"] as const;

// ---------------------------------------------------------------------------
// Relationships (the edge vocabulary) and entities
// ---------------------------------------------------------------------------

export interface RelationshipDef {
  id: string;
  label: string;
  /** Human sentence: "A {label} B". */
  inverse?: string;
}

export const RELATIONSHIP_TYPES: RelationshipDef[] = [
  { id: "complements", label: "complements", inverse: "complements" },
  { id: "related_to", label: "is related to", inverse: "related_to" },
  { id: "contradicts", label: "contradicts", inverse: "contradicts" },
  { id: "supersedes", label: "supersedes", inverse: "superseded_by" },
  { id: "superseded_by", label: "is superseded by", inverse: "supersedes" },
  { id: "enriched_by", label: "is enriched by", inverse: "enriches" },
  { id: "enriches", label: "enriches", inverse: "enriched_by" },
  { id: "derived_from", label: "is derived from", inverse: "source_of" },
  { id: "source_of", label: "is the source of", inverse: "derived_from" },
  { id: "applied_in", label: "was applied in", inverse: "applies" },
  { id: "taught_in", label: "was taught in", inverse: "teaches" },
  { id: "validated_by", label: "is validated by", inverse: "validates" },
  { id: "implemented_in", label: "is implemented in", inverse: "implements" },
  { id: "implements", label: "implements", inverse: "implemented_in" },
  { id: "used_playbook", label: "used the playbook", inverse: "used_by" },
  { id: "uses_evidence", label: "uses evidence", inverse: "evidence_for" },
  { id: "evidence_for", label: "is evidence for", inverse: "uses_evidence" },
  { id: "produced_result", label: "produced the result", inverse: "result_of" },
  { id: "led_to", label: "led to", inverse: "came_from" },
  { id: "adapted_into", label: "was adapted into", inverse: "adapted_from" },
  { id: "adapted_from", label: "was adapted from", inverse: "adapted_into" },
  { id: "produced_content", label: "produced the content", inverse: "based_on" },
];

export const RELATIONSHIP_IDS = RELATIONSHIP_TYPES.map((r) => r.id);

export function isRelationshipType(v: unknown): v is string {
  return typeof v === "string" && RELATIONSHIP_IDS.includes(v);
}

export function relationshipLabel(id: string): string {
  return RELATIONSHIP_TYPES.find((r) => r.id === id)?.label ?? humanize(id);
}

export const ENTITY_KINDS = [
  "person",
  "department",
  "client",
  "prospect",
  "offer",
  "product",
  "campaign",
  "platform",
  "framework",
  "project",
  "experiment",
  "content",
  "meeting",
  "kpi",
  "market",
] as const;
export type EntityKind = (typeof ENTITY_KINDS)[number];

export function isEntityKind(v: unknown): v is EntityKind {
  return typeof v === "string" && (ENTITY_KINDS as readonly string[]).includes(v);
}

// ---------------------------------------------------------------------------
// Stable refs + slugs
// ---------------------------------------------------------------------------

/** Ref prefix for an object (MG-001, DEC-014, PI-LI-003 …). */
export function refPrefix(o: {
  intelligence_class: IntelligenceClass;
  domain?: string | null;
  object_type?: string | null;
}): string {
  if (o.intelligence_class === "organizational_learning") {
    return LEARNING_REF_PREFIX[o.object_type ?? ""] ?? "LRN";
  }
  if (o.intelligence_class === "platform_intelligence") {
    const p = (o.domain === "platform" ? "" : o.domain ?? "").toUpperCase().slice(0, 2);
    return p ? `PI-${p}` : "PI";
  }
  if (o.intelligence_class === "performance_memory") return "PERF";
  if (o.intelligence_class === "raw_archive") return "RAW";
  const dom = DOMAINS.find((d) => d.id === o.domain)?.prefix ?? "GEN";
  return o.intelligence_class === "business_reality" ? `BR-${dom}` : dom;
}

/** Format a ref from a prefix and a sequence number: MG + 7 → "MG-007". */
export function formatRef(prefix: string, n: number): string {
  return `${prefix}-${String(Math.max(1, Math.floor(n))).padStart(3, "0")}`;
}

/** Lower-case snake slug for taxonomy values ("Management Leverage" → "management_leverage"). */
export function slugify(s: string): string {
  return (s || "")
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 64);
}

/** "management_leverage" → "Management leverage". */
export function humanize(s: string): string {
  const t = (s || "").replace(/[_-]+/g, " ").trim();
  return t ? t.charAt(0).toUpperCase() + t.slice(1) : "";
}

/** Jaccard-ish similarity of two slugs' token sets, for taxonomy reconciliation. */
export function slugSimilarity(a: string, b: string): number {
  const ta = new Set(slugify(a).split("_").filter(Boolean));
  const tb = new Set(slugify(b).split("_").filter(Boolean));
  if (ta.size === 0 || tb.size === 0) return 0;
  let inter = 0;
  for (const t of ta) if (tb.has(t)) inter++;
  const union = ta.size + tb.size - inter;
  const jac = inter / union;
  // Prefix containment bonus: "delegation" vs "delegation_rights".
  const sa = slugify(a);
  const sb = slugify(b);
  const contains = sa.length >= 4 && (sb.startsWith(sa) || sa.startsWith(sb)) ? 0.2 : 0;
  return Math.min(1, jac + contains);
}

/** Pick the closest existing taxonomy value for a proposed one, or null if nothing fits. */
export function reconcileValue(
  proposed: string,
  existing: string[],
  threshold = 0.6
): { value: string; similarity: number } | null {
  const p = slugify(proposed);
  if (!p) return null;
  let best: { value: string; similarity: number } | null = null;
  for (const e of existing) {
    if (slugify(e) === p) return { value: e, similarity: 1 };
    const sim = slugSimilarity(p, e);
    if (sim >= threshold && (!best || sim > best.similarity)) best = { value: e, similarity: sim };
  }
  return best;
}
